ARG PHP_VERSION=7.4

FROM kouinkouin/php-fpm:$PHP_VERSION

RUN wget -qO /etc/apt/trusted.gpg.d/php.gpg https://packages.sury.org/php/apt.gpg && \
    echo "deb https://packages.sury.org/php/ buster main" > /etc/apt/sources.list.d/php.list && \
    apt-get update

RUN \
    apt-get install -y \
        php7.4-xdebug \
        && \
    apt-get clean && \
    rm -r /var/lib/apt/lists/*

COPY files/conf.d/99-xdebug.ini /etc/php/fpm/conf.d/99-xdebug.ini
